version: "3.8"

services:
  db:
    image: postgres
    container_name: postgres
    mem_limit: 512mb
    mem_reservation: 512mb
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: main

